Check 13

diff --git a/.github/workflows/pull_request_merge_checks.yaml b/.github/workflows/pull_request_merge_checks.yaml
--- a/.github/workflows/pull_request_merge_checks.yaml
+++ b/.github/workflows/pull_request_merge_checks.yaml
@@ -227,24 +227,16 @@ jobs:
     needs:
       - build-summary-graphQL
       - build-summary-openAPI
-  if: always()
-  runs-on: ubuntu-latest
-  steps:
-    - name: Checkout code
-      uses: actions/checkout@v4
-    - name: Check OpenAPI and GraphQL Summary
-      run: |
-        # Check if any OpenAPI related jobs failed
-        if [[ "${{ needs.build-summary-openAPI.result }}" == "failure" ]]; then
-          echo "OpenAPI related jobs failed!"
-          exit 1
-        fi
-
-        # Check if any GraphQL related jobs failed
-        if [[ "${{ needs.build-summary-graphQL.result }}" == "failure" ]]; then
-          echo "GraphQL related jobs failed!"
-          exit 1
-        fi
-
-        # If no failures, print success message
-        echo "All build jobs completed successfully!"
+    if: always()
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+      - name: Check OpenAPI and GraphQL Summary
+        run: >
+          if [[ "${{ needs.build-summary-openAPI.result }}" == "failure" ]];
+          then echo "OpenAPI related jobs failed!" exit 1 fi if [[ "${{
+          needs.build-summary-graphQL.result }}" == "failure" ]]; then
+            echo "GraphQL related jobs failed!"
+            exit 1
+          fi echo "All build jobs completed successfully!"
